=== AngeloTrifelli/Esercizio-XML-DOM/associazioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaAssociazioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="associazione" minOccurs="0" maxOccurs="unbounded" />        
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="associazione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="biglietto" minOccurs="1" maxOccurs="1" />
                <xsd:element name="artista" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="id" use="required">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minExclusive value="0" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
            <xsd:attribute name="numPosti" use="required">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minExclusive value="0" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="biglietto" type="xsd:string" />
    <xsd:element name="artista" type="xsd:string" />

</xsd:schema>

=== AngeloTrifelli/Esercizio-XML-DOM/associazioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaAssociazioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="associazioni.xsd">
    <associazione id="1" numPosti="300">
        <biglietto>
            BASIC
        </biglietto>
        <artista>
            Blanco
        </artista>
    </associazione>
    <associazione id="2" numPosti="200">
        <biglietto>
            DELUXE
        </biglietto>
        <artista>
            Blanco
        </artista>
    </associazione>
    <associazione id="3" numPosti="100">
        <biglietto>
            PREMIUM
        </biglietto>
        <artista>
            Blanco
        </artista>
    </associazione>
    <associazione id="4" numPosti="250">
        <biglietto>
            BASIC
        </biglietto>
        <artista>
            Green Day
        </artista>
    </associazione>
    <associazione id="5" numPosti="150">
        <biglietto>
            PREMIUM
        </biglietto>
        <artista>
            Green Day
        </artista>
    </associazione>
    <associazione id="6" numPosti="200">
        <biglietto>
            BASIC
        </biglietto>
        <artista>
            Pink Floyd
        </artista>
    </associazione>
</listaAssociazioni>
