=== AngeloTrifelli/Esercizio-XML-DOM/utenti.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT listaUtenti (utente*)>
<!ELEMENT utente (nome,cognome,dataDiNascita,indirizzoDomicilio?,credenziali)>
<!ATTLIST utente 
    codFisc CDATA #REQUIRED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT cognome (#PCDATA)>
<!ELEMENT dataDiNascita (giorno,mese,anno)>
<!ELEMENT indirizzoDomicilio (via,civico)>
<!ELEMENT credenziali (email,password)>
<!ELEMENT giorno (#PCDATA)>
<!ELEMENT mese (#PCDATA)>
<!ELEMENT anno (#PCDATA)>
<!ELEMENT via (#PCDATA)>
<!ELEMENT civico (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== AngeloTrifelli/Esercizio-XML-DOM/utenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaUtenti SYSTEM "utenti.dtd">
<listaUtenti>
     <utente codFisc="RSSGNN64R03E472G">
         <nome>
            Giovanni
        </nome>
        <cognome>
            Rossi
        </cognome>
        <dataDiNascita>
            <giorno>
                3
            </giorno>
            <mese>
                10
            </mese>
            <anno>
                1964
            </anno>
        </dataDiNascita>
        <indirizzoDomicilio>
            <via>
                del quasimodo
            </via>
            <civico>
                13
            </civico>
        </indirizzoDomicilio>
        <prenotazione>
            <nomeArtista>
                Green Day
            </nomeArtista>
            <tipoBiglietto>
                BASIC
            </tipoBiglietto>
        </prenotazione>
        <credenziali>
            <email>
                giovanni.rossi64@gmail.com
            </email>
            <password>
                Giovanni64
            </password>
        </credenziali>
    </utente>
</listaUtenti>
